const m = (x) => BigInt.asIntN(64, x);
const u = (x) => BigInt.asUintN(64, x);
export const fromInt = (a) => BigInt(a | 0);
export const toInt = (a) => Number(BigInt.asIntN(32, a));
export const and = (a) => (b) => m(a & b);
export const or = (a) => (b) => m(a | b);
export const xor = (a) => (b) => m(a ^ b);
export const complement = (a) => m(~a);
export const shl = (a) => (b) => m(a << (b & 63n));
export const shr = (a) => (b) => m(a >> (b & 63n));
export const zshr = (a) => (b) => m(u(a) >> (b & 63n));
export const rotl = (a) => (b) => { const n = b & 63n; return m((a << n) | (u(a) >> (64n - n))); };
export const rotr = (a) => (b) => { const n = b & 63n; return m((u(a) >> n) | (a << (64n - n))); };
export const eq = (a) => (b) => a === b;
export const lt = (a) => (b) => a < b;